# 饿了么 
^https:\/\/(nr-op|cube)\.elemecdn\.com\/.+\.jpeg\?x-oss-process=image\/resize,m_fill,w_\d{4,},h_\d{4,}\/($|format,webp\/$) url reject-dict
#苏周到 屏蔽更新提示
^https:\/\/szdmobile.suzhou\.gov\.cn\/thirdapp-center\/appUpdate\/update url reject-dict
#苏e行
^https?:\/\/api\.bwton\.com\/bas\/ad url reject-dict
^https:\/\/api\.bwton\.com\/bff\/app\/index\/goods url reject-dict
^https:\/\/api\.bwton\.com\/bff\/app\/index\/recommend url reject-dict
#宝宝树孕育
^https?:\/\/plough\.babytree\.com\/plough\.do url reject-dict
#顺丰速运小程序
^https?:\/\/ucmp\.sf-express\.com\/cx-wechat-query\/query\/info-flow\/reconsitution-list url reject-200
# 美团
^https:\/\/img\.meituan\.net\/bizad\/bizad_brandCpt_\d+ url reject-dict
^https?:\/\/s3plus\.meituan\.net\/v1\/mss_\w+\/(brandcpt-vedio|waimai-alita)\/\w+\?? url reject

hostname = cube.elemecdn.com,nr-op.elemecdn.com,szdmobile.suzhou.gov.cn,api.bwton.com,plough.babytree.com,ucmp.sf-express.com,img.meituan.net,s3plus.meituan.net
