#G重定向
^https?://(www.)?(g|google).cn url 302 https://www.google.com
# 京东
^https?:\/\/api\.m\.jd\.com\/client\.action\?functionId=(start|queryMaterialAdverts) url reject-dict
^https?:\/\/api\.m\.jd\.com\/client\.action\?functionId=(hotWords|hotSearchTerms) url script-response-body https://github.com/ddgksf2013/Scripts/raw/master/jd_json.js
#京东极速版
^https?:\/\/api\.m\.jd\.com\/client\.action\?functionId=lite_advertising url response-body jdLiteAdvertisingVO response-body ddgksf2013
^https?:\/\/api\.m\.jd\.com\/client\.action\?functionId=lite_SmartPush url response-body pushData response-body ddgksf2013
# 饿了么 
^https:\/\/elemecdn.com\/.+\/sitemap url reject-dict
^https:\/\/fuss10.elemecdn.com\/.+\/w\/750\/h\/\d{3,4} url reject-dict
^https:\/\/(nr-op|cube)\.elemecdn\.com\/.+\.jpeg\?x-oss-process=image\/resize,m_fill,w_\d{4,},h_\d{4,}\/($|format,webp\/$) url reject-dict
#苏周到 屏蔽更新提示
^https:\/\/szdmobile\.suzhou\.gov\.cn\/thirdapp-center\/appUpdate\/update url reject-dict
#苏e行
^https?:\/\/api\.bwton\.com\/bas\/ad url reject-200
#宝宝树孕育
^https?:\/\/plough\.babytree\.com\/plough\.do url reject-200
#顺丰速运小程序
^https?:\/\/ucmp\.sf-express\.com\/cx-wechat-query\/query\/info-flow\/reconsitution-list url reject-200
#豆瓣补充
^https:\/\/api\.douban\.com\b.*\/common_ads\? url reject-dict
# 美团
^https:\/\/img\.meituan\.net\/bizad\/bizad_brandCpt_\d+ url reject-dict
^https?:\/\/s3plus\.meituan\.net\/v1\/mss_\w+\/(brandcpt-vedio|waimai-alita)\/\w+\?? url reject-dict

hostname = www.google.cn,api.m.jd.com,elemecdn.com,cube.elemecdn.com,nr-op.elemecdn.com,szdmobile.suzhou.gov.cn,api.bwton.com,plough.babytree.com,ucmp.sf-express.com,img.meituan.net,s3plus.meituan.net
