[rewrite_remote]
#喜马拉雅(不用搬会员数据了，定期改密码)
https://raw.githubusercontent.com/WeiRen0/Scripts/main/ximalaya.js, tag=伟人解锁-喜马拉雅, update-interval=172800, opt-parser=false, enabled=false

#酷我音乐(新版全功能解锁+最完美版)
https://raw.githubusercontent.com/WeiRen0/Scripts/main/kw.js, tag=伟人解锁-酷我音乐, update-interval=172800, opt-parser=false, enabled=false

#网易云解锁VIP直接听
https://raw.githubusercontent.com/WeiRen0/Scripts/main/wyun.js, tag=伟人解锁-网易云解锁VIP, update-interval=172800, opt-parser=false, enabled=false
